### ISSUE TITLE
Adding of image not working

### ISSUE THREAD

**Issue by huxley27** [renebigot/XlsxReaderWriter#9]
Hi renebigot. I can't make it work when adding image to my excel file. following this

UIImage *image = [UIImage imageNamed:@"Kitten.jpeg"];
//preserveTransparency force JPEG (NO) or PNG (YES)
BRAWorksheetDrawing *drawing = [worksheet addImage:image betweenCellsReferenced:@"G2" and:@"I10"
                                        withInsets:UIEdgeInsetsZero preserveTransparency:NO];
//Set drawing insets (percentage)
drawing.insets = UIEdgeInsetsMake(0., 0., .5, .5);

It doesn't throw any errors but by the time I open the file, there's no images added. I'm sure that the image is valid png file and added to the target of my project. Is there something missing that I've done?

thank you!

**Comment by renebigot** [comment]
Hi @huxley27,

I think it's a bug that I've fixed on my current version, but I haven't push it yet. I'll try to push it today.

Cheers

**Comment by huxley27** [comment]
thank you so much!!! :)

**Comment by renebigot** [comment]
I've just pushed some code. Let me know if it works.

**Comment by huxley27** [comment]
Hi rene,

its still not working :( I pulled the latest code but no images was
inserted into my excel file. here's my code in viewdidload.

NSString *documentPath = [[NSBundle mainBundle] pathForResource:@"report"
ofType:@"xlsx"];
    BRAOfficeDocumentPackage *spreadsheet = [BRAOfficeDocumentPackage
open:documentPath];

    //First worksheet in the workbook
    BRAWorksheet *worksheet = spreadsheet.workbook.worksheets[0];

    UIImage *image = [UIImage imageNamed:@"sample.jpg"];
    //preserveTransparency force JPEG (NO) or PNG (YES)
    BRAWorksheetDrawing *drawing = [worksheet addImage:image
betweenCellsReferenced:@"G2" and:@"I10"
                                            withInsets:UIEdgeInsetsZero
preserveTransparency:NO];
    //Set drawing insets (percentage)
    drawing.insets = UIEdgeInsetsMake(0., 0., .5, .5);

    //Savesa
    [spreadsheet save];

    //Save a copy
    NSString *fullPath =
[[NSSearchPathForDirectoriesInDomains(NSDocumentDirectory,
NSUserDomainMask, YES) lastObject] stringByAppendingPathComponent:@
"workbookCopy.xlsx"];
    [spreadsheet saveAs:fullPath];

**Comment by renebigot** [comment]
I've just tested your code. It works for me.
Have you test if your UIImage value is not nil ?

**Comment by huxley27** [comment]
yes i tested my image and used different images. i was able to display it
also in uiimageview. I created the excel file using my mac. there's ms
office installed and I saved a blank .xlsx file and added that to my
project as a resource. I was able to insert formula and other stuff. can
you send me your sample excel file and use that?

**Comment by renebigot** [comment]
I've used the file included for unit testing, it is named testWorkbook.xlsx.
Run the unit tests and watch the logs. The logs will contain some line containing "------ WORKING DIRECTORY".
Open that directory and find a file named testAddTwoCellAnchoredImage.xlsx inside. Does it contain a picture in G2-H9 ?

**Comment by byronCODE** [comment]
hi renebigot,I got the same issues of added image could you post a demo that can insert image in excel ,or send me a demo,thank you

**Comment by renebigot** [comment]
HI @byronCODE. There's a demo in the unit tests.

**Comment by byronCODE** [comment]
thank you @renebigot, it's really helpful

**Comment by huxley27** [comment]
I used your xlsx file and it worked. thank you Merry Christmas also

**Comment by renebigot** [comment]
Cool !
Thanks @huxley27 and merry Christmas to both of you
